[colors.primary]
background = '#121414'
foreground = '#ffffff'
 
[colors.cursor]
text = '#ffffff'
cursor = '#ffffff' 
 
[colors.vi_mode_cursor]
text = '#121414'
cursor = '#d8f5ff' 
 
[colors.search.matches]
foreground = '#41484a' 
background = '#f9ecff' 
 
[colors.search.focused_match]
foreground = '#41484a' 
background = '#d8f5ff' 
 
[colors.footer_bar]
foreground = '#41484a' 
background = '#e2e2e3' 
 
[colors.hints.start]
foreground = '#41484a' 
background = '#e4f2f8' 
 
[colors.hints.end]
foreground = '#41484a' 
background = '#e4f2f8' 
 
[colors.selection]
text = '#121414'
background = '#d8f5ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffece9' 
green = '#d8f5ff' 
yellow = '#274d58' 
blue = '#d8f5ff' 
magenta = '#f9ecff' 
cyan = '#e4f2f8' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
