[colors.primary]
background = '#0e1415'
foreground = '#dde4e4'
 
[colors.cursor]
text = '#dde4e4'
cursor = '#bec8c9' 
 
[colors.vi_mode_cursor]
text = '#0e1415'
cursor = '#80d4da' 
 
[colors.search.matches]
foreground = '#3f4949' 
background = '#b6c7e9' 
 
[colors.search.focused_match]
foreground = '#3f4949' 
background = '#80d4da' 
 
[colors.footer_bar]
foreground = '#3f4949' 
background = '#dde4e4' 
 
[colors.hints.start]
foreground = '#3f4949' 
background = '#b1cccd' 
 
[colors.hints.end]
foreground = '#3f4949' 
background = '#b1cccd' 
 
[colors.selection]
text = '#0e1415'
background = '#80d4da'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#80d4da' 
yellow = '#00696e' 
blue = '#80d4da' 
magenta = '#b6c7e9' 
cyan = '#b1cccd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
