[colors.primary]
background = '#17130b'
foreground = '#ece1d4'
 
[colors.cursor]
text = '#ece1d4'
cursor = '#d2c5b4' 
 
[colors.vi_mode_cursor]
text = '#17130b'
cursor = '#eebf6d' 
 
[colors.search.matches]
foreground = '#4e4639' 
background = '#b4cea5' 
 
[colors.search.focused_match]
foreground = '#4e4639' 
background = '#eebf6d' 
 
[colors.footer_bar]
foreground = '#4e4639' 
background = '#ece1d4' 
 
[colors.hints.start]
foreground = '#4e4639' 
background = '#dac3a1' 
 
[colors.hints.end]
foreground = '#4e4639' 
background = '#dac3a1' 
 
[colors.selection]
text = '#17130b'
background = '#eebf6d'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#eebf6d' 
yellow = '#7b580d' 
blue = '#eebf6d' 
magenta = '#b4cea5' 
cyan = '#dac3a1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
