[colors.primary]
background = '#191118'
foreground = '#ffffff'
 
[colors.cursor]
text = '#ffffff'
cursor = '#ffffff' 
 
[colors.vi_mode_cursor]
text = '#191118'
cursor = '#ffeaf9' 
 
[colors.search.matches]
foreground = '#51424f' 
background = '#ffebed' 
 
[colors.search.focused_match]
foreground = '#51424f' 
background = '#ffeaf9' 
 
[colors.footer_bar]
foreground = '#51424f' 
background = '#eedee8' 
 
[colors.hints.start]
foreground = '#51424f' 
background = '#ffeaf9' 
 
[colors.hints.end]
foreground = '#51424f' 
background = '#ffeaf9' 
 
[colors.selection]
text = '#191118'
background = '#ffeaf9'
 
 
[colors.normal]
black = '#181818' 
red = '#ffece9' 
green = '#ffeaf9' 
yellow = '#7f0886' 
blue = '#ffeaf9' 
magenta = '#ffebed' 
cyan = '#ffeaf9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
