[colors.primary]
background = '#191113'
foreground = '#efdfe1'
 
[colors.cursor]
text = '#efdfe1'
cursor = '#d6c2c5' 
 
[colors.vi_mode_cursor]
text = '#191113'
cursor = '#ffb1c5' 
 
[colors.search.matches]
foreground = '#514346' 
background = '#eebd92' 
 
[colors.search.focused_match]
foreground = '#514346' 
background = '#ffb1c5' 
 
[colors.footer_bar]
foreground = '#514346' 
background = '#efdfe1' 
 
[colors.hints.start]
foreground = '#514346' 
background = '#e3bdc5' 
 
[colors.hints.end]
foreground = '#514346' 
background = '#e3bdc5' 
 
[colors.selection]
text = '#191113'
background = '#ffb1c5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb1c5' 
yellow = '#8c4a5d' 
blue = '#ffb1c5' 
magenta = '#eebd92' 
cyan = '#e3bdc5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
