[colors.primary]
background = '#13140d'
foreground = '#e4e3d7'
 
[colors.cursor]
text = '#e4e3d7'
cursor = '#c7c8b8' 
 
[colors.vi_mode_cursor]
text = '#13140d'
cursor = '#bdce80' 
 
[colors.search.matches]
foreground = '#46483c' 
background = '#a1d0c5' 
 
[colors.search.focused_match]
foreground = '#46483c' 
background = '#bdce80' 
 
[colors.footer_bar]
foreground = '#46483c' 
background = '#e4e3d7' 
 
[colors.hints.start]
foreground = '#46483c' 
background = '#c4caa9' 
 
[colors.hints.end]
foreground = '#46483c' 
background = '#c4caa9' 
 
[colors.selection]
text = '#13140d'
background = '#bdce80'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bdce80' 
yellow = '#556423' 
blue = '#bdce80' 
magenta = '#a1d0c5' 
cyan = '#c4caa9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
