[colors.primary]
background = '#15130b'
foreground = '#e8e2d4'
 
[colors.cursor]
text = '#e8e2d4'
cursor = '#cdc6b4' 
 
[colors.vi_mode_cursor]
text = '#15130b'
cursor = '#dbc66f' 
 
[colors.search.matches]
foreground = '#4b4739' 
background = '#a9d0b3' 
 
[colors.search.focused_match]
foreground = '#4b4739' 
background = '#dbc66f' 
 
[colors.footer_bar]
foreground = '#4b4739' 
background = '#e8e2d4' 
 
[colors.hints.start]
foreground = '#4b4739' 
background = '#d1c6a1' 
 
[colors.hints.end]
foreground = '#4b4739' 
background = '#d1c6a1' 
 
[colors.selection]
text = '#15130b'
background = '#dbc66f'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#dbc66f' 
yellow = '#6d5e0f' 
blue = '#dbc66f' 
magenta = '#a9d0b3' 
cyan = '#d1c6a1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
