[colors.primary]
background = '#f4fbf9'
foreground = '#161d1c'
 
[colors.cursor]
text = '#161d1c'
cursor = '#3f4947' 
 
[colors.vi_mode_cursor]
text = '#f4fbf9'
cursor = '#006a65' 
 
[colors.search.matches]
foreground = '#dae5e3' 
background = '#48607b' 
 
[colors.search.focused_match]
foreground = '#dae5e3' 
background = '#006a65' 
 
[colors.footer_bar]
foreground = '#dae5e3' 
background = '#2b3231' 
 
[colors.hints.start]
foreground = '#dae5e3' 
background = '#4a6361' 
 
[colors.hints.end]
foreground = '#dae5e3' 
background = '#4a6361' 
 
[colors.selection]
text = '#f4fbf9'
background = '#006a65'
 
 
[colors.normal]
black = '#181818' 
red = '#ba1a1a' 
green = '#006a65' 
yellow = '#81d5ce' 
blue = '#006a65' 
magenta = '#48607b' 
cyan = '#4a6361' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
