[colors.primary]
background = '#101417'
foreground = '#ffffff'
 
[colors.cursor]
text = '#ffffff'
cursor = '#ffffff' 
 
[colors.vi_mode_cursor]
text = '#101417'
cursor = '#e3f2ff' 
 
[colors.search.matches]
foreground = '#41484d' 
background = '#f5edff' 
 
[colors.search.focused_match]
foreground = '#41484d' 
background = '#e3f2ff' 
 
[colors.footer_bar]
foreground = '#41484d' 
background = '#dfe3e7' 
 
[colors.hints.start]
foreground = '#41484d' 
background = '#e3f2ff' 
 
[colors.hints.end]
foreground = '#41484d' 
background = '#e3f2ff' 
 
[colors.selection]
text = '#101417'
background = '#e3f2ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffece9' 
green = '#e3f2ff' 
yellow = '#004d6e' 
blue = '#e3f2ff' 
magenta = '#f5edff' 
cyan = '#e3f2ff' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
