[colors.primary]
background = '#16130b'
foreground = '#e9e2d4'
 
[colors.cursor]
text = '#e9e2d4'
cursor = '#cdc6b4' 
 
[colors.vi_mode_cursor]
text = '#16130b'
cursor = '#dcc66e' 
 
[colors.search.matches]
foreground = '#4b4739' 
background = '#aad0b2' 
 
[colors.search.focused_match]
foreground = '#4b4739' 
background = '#dcc66e' 
 
[colors.footer_bar]
foreground = '#4b4739' 
background = '#e9e2d4' 
 
[colors.hints.start]
foreground = '#4b4739' 
background = '#d2c6a1' 
 
[colors.hints.end]
foreground = '#4b4739' 
background = '#d2c6a1' 
 
[colors.selection]
text = '#16130b'
background = '#dcc66e'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#dcc66e' 
yellow = '#6e5d0e' 
blue = '#dcc66e' 
magenta = '#aad0b2' 
cyan = '#d2c6a1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
