# : Manager [[[

[mgr]
cwd = { fg = "#efdfe1" }

# Tab
tab_active = { fg = "#551d2f", bg = "#ffb1c5", bold = true }
tab_inactive = { fg = "#ffd9e1", bg = "#3a071b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffa459", bg = "#ffa459" }
marker_cut = { fg = "#ffdcbf", bg = "#ffdcbf" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eebd92", bg = "#eebd92" }

# Count
count_copied = { fg = "#2d1600", bg = "#ffdcbf" }
count_cut = { fg = "#2d1600", bg = "#ffdcbf" }
count_selected = { fg = "#551d2f", bg = "#eebd92" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb1c5" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#551d2f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb1c5", fg = "#551d2f", bold = true }
normal_alt  = { bg = "#514346", fg = "#d6c2c5" }

# Select mode
select_main = { bg = "#e3bdc5", fg = "#422930", bold = true }
select_alt  = { bg = "#514346", fg = "#d6c2c5" }

# Unset mode
unset_main = { bg = "#eebd92", fg = "#472a0a", bold = true }
unset_alt  = { bg = "#514346", fg = "#d6c2c5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb1c5", bg = "#413739" }
progress_error = { fg = "#ffb4ab", bg = "#413739" }

# Permissions
permissions_t = { fg = "#b55267" }
permissions_w = { fg = "#c86e1f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff8826" }
permissions_s = { fg = "#ff4068" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb1c5" }
active = { fg = "#eebd92", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1c5" }
value = { fg = "#efdfe1" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb1c5", bold = true, bg = "#191113" }
inactive = { fg = "#e3bdc5", bg = "#191113" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb1c5", bg = "#551d2f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb1c5" }
title = {}
hovered = { fg = "#ffdcbf", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413739" }
cand = { fg = "#ffb1c5" }
rest = { fg = "#551d2f" }
desc = { fg = "#efdfe1" }
separator = " ‚ñ∂ "
separator_style = { fg = "#efdfe1" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efdfe1" }
run = { fg = "#efdfe1" }
footer = { fg = "#422930", bg = "#e3bdc5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#eebd92" }
title_warn = { fg = "#ffb1c5" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#efdfe1" },
    { name = "*/", fg = "#ffb1c5" },
]

# : ]]]
