# : Manager [[[

[mgr]
cwd = { fg = "#ece1d4" }

# Tab
tab_active = { fg = "#422c00", bg = "#eebf6d", bold = true }
tab_inactive = { fg = "#ffdeaa", bg = "#271900" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#94d273", bg = "#94d273" }
marker_cut = { fg = "#cfebc0", bg = "#cfebc0" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b4cea5", bg = "#b4cea5" }

# Count
count_copied = { fg = "#0c2006", bg = "#cfebc0" }
count_cut = { fg = "#0c2006", bg = "#cfebc0" }
count_selected = { fg = "#422c00", bg = "#b4cea5" }

# Border
border_symbol = " "
border_style  = { fg = "#eebf6d" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#422c00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#eebf6d", fg = "#422c00", bold = true }
normal_alt  = { bg = "#4e4639", fg = "#d2c5b4" }

# Select mode
select_main = { bg = "#dac3a1", fg = "#3c2e16", bold = true }
select_alt  = { bg = "#4e4639", fg = "#d2c5b4" }

# Unset mode
unset_main = { bg = "#b4cea5", fg = "#203619", bold = true }
unset_alt  = { bg = "#4e4639", fg = "#d2c5b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#eebf6d", bg = "#3e382f" }
progress_error = { fg = "#ffb4ab", bg = "#3e382f" }

# Permissions
permissions_t = { fg = "#a27a40" }
permissions_w = { fg = "#648d4d" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#77c64c" }
permissions_s = { fg = "#ffa311" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#eebf6d" }
active = { fg = "#b4cea5", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#eebf6d" }
value = { fg = "#ece1d4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#eebf6d", bold = true, bg = "#17130b" }
inactive = { fg = "#dac3a1", bg = "#17130b" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#eebf6d", bg = "#422c00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#eebf6d" }
title = {}
hovered = { fg = "#cfebc0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3e382f" }
cand = { fg = "#eebf6d" }
rest = { fg = "#422c00" }
desc = { fg = "#ece1d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ece1d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ece1d4" }
run = { fg = "#ece1d4" }
footer = { fg = "#3c2e16", bg = "#dac3a1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b4cea5" }
title_warn = { fg = "#eebf6d" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ece1d4" },
    { name = "*/", fg = "#eebf6d" },
]

# : ]]]
