# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#ffece7", bold = true }
tab_inactive = { fg = "#ffdbd1", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ebc24b", bg = "#ebc24b" }
marker_cut = { fg = "#f5e1a7", bg = "#f5e1a7" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#ffefc3", bg = "#ffefc3" }

# Count
count_copied = { fg = "#000000", bg = "#f5e1a7" }
count_cut = { fg = "#000000", bg = "#f5e1a7" }
count_selected = { fg = "#000000", bg = "#ffefc3" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb59f" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffece7", fg = "#000000", bold = true }
normal_alt  = { bg = "#53433f", fg = "#ffffff" }

# Select mode
select_main = { bg = "#ffece7", fg = "#000000", bold = true }
select_alt  = { bg = "#53433f", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#ffefc3", fg = "#000000", bold = true }
unset_alt  = { bg = "#53433f", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffece7", bg = "#5a4d4a" }
progress_error = { fg = "#ffece9", bg = "#5a4d4a" }

# Permissions
permissions_t = { fg = "#ff734e" }
permissions_w = { fg = "#ffc62a" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#e5b21e" }
permissions_s = { fg = "#ff6338" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffece7" }
active = { fg = "#ffefc3", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffece7" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffece7", bold = true, bg = "#1a110f" }
inactive = { fg = "#ffece7", bg = "#1a110f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffece7", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffece7" }
title = {}
hovered = { fg = "#f5e1a7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#5a4d4a" }
cand = { fg = "#ffece7" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#ffece7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffefc3" }
title_warn = { fg = "#ffece7" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#ffb59f" },
]

# : ]]]
