# : Manager [[[

[mgr]
cwd = { fg = "#dfe4dc" }

# Tab
tab_active = { fg = "#003916", bg = "#9ad4a1", bold = true }
tab_inactive = { fg = "#b5f1bc", bg = "#00210a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#66cee5", bg = "#66cee5" }
marker_cut = { fg = "#bdeaf4", bg = "#bdeaf4" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a1ced8", bg = "#a1ced8" }

# Count
count_copied = { fg = "#001f25", bg = "#bdeaf4" }
count_cut = { fg = "#001f25", bg = "#bdeaf4" }
count_selected = { fg = "#003916", bg = "#a1ced8" }

# Border
border_symbol = " "
border_style  = { fg = "#9ad4a1" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003916", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#9ad4a1", fg = "#003916", bold = true }
normal_alt  = { bg = "#414941", fg = "#c1c9be" }

# Select mode
select_main = { bg = "#b7ccb6", fg = "#233425", bold = true }
select_alt  = { bg = "#414941", fg = "#c1c9be" }

# Unset mode
unset_main = { bg = "#a1ced8", fg = "#00363e", bold = true }
unset_alt  = { bg = "#414941", fg = "#c1c9be" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#9ad4a1", bg = "#363a35" }
progress_error = { fg = "#ffb4ab", bg = "#363a35" }

# Permissions
permissions_t = { fg = "#628960" }
permissions_w = { fg = "#428d9e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3ac0de" }
permissions_s = { fg = "#34d948" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#9ad4a1" }
active = { fg = "#a1ced8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#9ad4a1" }
value = { fg = "#dfe4dc" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#9ad4a1", bold = true, bg = "#101510" }
inactive = { fg = "#b7ccb6", bg = "#101510" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#9ad4a1", bg = "#003916" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#9ad4a1" }
title = {}
hovered = { fg = "#bdeaf4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a35" }
cand = { fg = "#9ad4a1" }
rest = { fg = "#003916" }
desc = { fg = "#dfe4dc" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dfe4dc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe4dc" }
run = { fg = "#dfe4dc" }
footer = { fg = "#233425", bg = "#b7ccb6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a1ced8" }
title_warn = { fg = "#9ad4a1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dfe4dc" },
    { name = "*/", fg = "#9ad4a1" },
]

# : ]]]
