# : Manager [[[

[mgr]
cwd = { fg = "#e4e3d7" }

# Tab
tab_active = { fg = "#293500", bg = "#bdce80", bold = true }
tab_inactive = { fg = "#d8eb9a", bg = "#171e00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6ed5bd", bg = "#6ed5bd" }
marker_cut = { fg = "#bdece1", bg = "#bdece1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a1d0c5", bg = "#a1d0c5" }

# Count
count_copied = { fg = "#00201b", bg = "#bdece1" }
count_cut = { fg = "#00201b", bg = "#bdece1" }
count_selected = { fg = "#293500", bg = "#a1d0c5" }

# Border
border_symbol = " "
border_style  = { fg = "#bdce80" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#293500", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bdce80", fg = "#293500", bold = true }
normal_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# Select mode
select_main = { bg = "#c4caa9", fg = "#2d331b", bold = true }
select_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# Unset mode
unset_main = { bg = "#a1d0c5", fg = "#033730", bold = true }
unset_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bdce80", bg = "#393a31" }
progress_error = { fg = "#ffb4ab", bg = "#393a31" }

# Permissions
permissions_t = { fg = "#7d8753" }
permissions_w = { fg = "#48907f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#46caab" }
permissions_s = { fg = "#a0c527" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bdce80" }
active = { fg = "#a1d0c5", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#bdce80" }
value = { fg = "#e4e3d7" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#bdce80", bold = true, bg = "#13140d" }
inactive = { fg = "#c4caa9", bg = "#13140d" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bdce80", bg = "#293500" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#bdce80" }
title = {}
hovered = { fg = "#bdece1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393a31" }
cand = { fg = "#bdce80" }
rest = { fg = "#293500" }
desc = { fg = "#e4e3d7" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e4e3d7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e3d7" }
run = { fg = "#e4e3d7" }
footer = { fg = "#2d331b", bg = "#c4caa9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a1d0c5" }
title_warn = { fg = "#bdce80" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e4e3d7" },
    { name = "*/", fg = "#bdce80" },
]

# : ]]]
