# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#d8f5ff", bold = true }
tab_inactive = { fg = "#c2e9f6", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c275ff", bg = "#c275ff" }
marker_cut = { fg = "#efdbff", bg = "#efdbff" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#f9ecff", bg = "#f9ecff" }

# Count
count_copied = { fg = "#000000", bg = "#efdbff" }
count_cut = { fg = "#000000", bg = "#efdbff" }
count_selected = { fg = "#000000", bg = "#f9ecff" }

# Border
border_symbol = " "
border_style  = { fg = "#a6cdd9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d8f5ff", fg = "#000000", bold = true }
normal_alt  = { bg = "#41484a", fg = "#ffffff" }

# Select mode
select_main = { bg = "#e4f2f8", fg = "#000000", bold = true }
select_alt  = { bg = "#41484a", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#f9ecff", fg = "#000000", bold = true }
unset_alt  = { bg = "#41484a", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d8f5ff", bg = "#4f5051" }
progress_error = { fg = "#ffece9", bg = "#4f5051" }

# Permissions
permissions_t = { fg = "#6bb8d9" }
permissions_w = { fg = "#c953ff" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#ab42ff" }
permissions_s = { fg = "#3db9e2" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d8f5ff" }
active = { fg = "#f9ecff", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#d8f5ff" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#d8f5ff", bold = true, bg = "#121414" }
inactive = { fg = "#e4f2f8", bg = "#121414" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d8f5ff", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d8f5ff" }
title = {}
hovered = { fg = "#efdbff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#4f5051" }
cand = { fg = "#d8f5ff" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#e4f2f8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f9ecff" }
title_warn = { fg = "#d8f5ff" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#a6cdd9" },
]

# : ]]]
