# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#ffeaf9", bold = true }
tab_inactive = { fg = "#ffd6f8", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7382", bg = "#ff7382" }
marker_cut = { fg = "#ffd9dd", bg = "#ffd9dd" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#ffebed", bg = "#ffebed" }

# Count
count_copied = { fg = "#000000", bg = "#ffd9dd" }
count_cut = { fg = "#000000", bg = "#ffd9dd" }
count_selected = { fg = "#000000", bg = "#ffebed" }

# Border
border_symbol = " "
border_style  = { fg = "#ffa9fa" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffeaf9", fg = "#000000", bold = true }
normal_alt  = { bg = "#51424f", fg = "#ffffff" }

# Select mode
select_main = { bg = "#ffeaf9", fg = "#000000", bold = true }
select_alt  = { bg = "#51424f", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#ffebed", fg = "#000000", bold = true }
unset_alt  = { bg = "#51424f", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffeaf9", bg = "#584d55" }
progress_error = { fg = "#ffece9", bg = "#584d55" }

# Permissions
permissions_t = { fg = "#ff51cd" }
permissions_w = { fg = "#ff5263" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#ff4054" }
permissions_s = { fg = "#ff3dde" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffeaf9" }
active = { fg = "#ffebed", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffeaf9" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffeaf9", bold = true, bg = "#191118" }
inactive = { fg = "#ffeaf9", bg = "#191118" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffeaf9", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffeaf9" }
title = {}
hovered = { fg = "#ffd9dd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#584d55" }
cand = { fg = "#ffeaf9" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#ffeaf9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffebed" }
title_warn = { fg = "#ffeaf9" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#ffa9fa" },
]

# : ]]]
