# : Manager [[[

[mgr]
cwd = { fg = "#dee4de" }

# Tab
tab_active = { fg = "#003825", bg = "#8dd5b2", bold = true }
tab_inactive = { fg = "#a9f2cd", bg = "#002114" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#61c7f5", bg = "#61c7f5" }
marker_cut = { fg = "#c1e9fb", bg = "#c1e9fb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a5ccde", bg = "#a5ccde" }

# Count
count_copied = { fg = "#001f29", bg = "#c1e9fb" }
count_cut = { fg = "#001f29", bg = "#c1e9fb" }
count_selected = { fg = "#003825", bg = "#a5ccde" }

# Border
border_symbol = " "
border_style  = { fg = "#8dd5b2" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003825", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#8dd5b2", fg = "#003825", bold = true }
normal_alt  = { bg = "#404943", fg = "#bfc9c1" }

# Select mode
select_main = { bg = "#b4ccbd", fg = "#1f352a", bold = true }
select_alt  = { bg = "#404943", fg = "#bfc9c1" }

# Unset mode
unset_main = { bg = "#a5ccde", fg = "#073543", bold = true }
unset_alt  = { bg = "#404943", fg = "#bfc9c1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8dd5b2", bg = "#353b37" }
progress_error = { fg = "#ffb4ab", bg = "#353b37" }

# Permissions
permissions_t = { fg = "#5e8a6e" }
permissions_w = { fg = "#3f89ab" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#31b6f2" }
permissions_s = { fg = "#24de80" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8dd5b2" }
active = { fg = "#a5ccde", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#8dd5b2" }
value = { fg = "#dee4de" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#8dd5b2", bold = true, bg = "#0f1511" }
inactive = { fg = "#b4ccbd", bg = "#0f1511" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8dd5b2", bg = "#003825" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8dd5b2" }
title = {}
hovered = { fg = "#c1e9fb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353b37" }
cand = { fg = "#8dd5b2" }
rest = { fg = "#003825" }
desc = { fg = "#dee4de" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee4de" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4de" }
run = { fg = "#dee4de" }
footer = { fg = "#1f352a", bg = "#b4ccbd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a5ccde" }
title_warn = { fg = "#8dd5b2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee4de" },
    { name = "*/", fg = "#8dd5b2" },
]

# : ]]]
