# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#ffedd7", bold = true }
tab_inactive = { fg = "#ffdeab", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#98d172", bg = "#98d172" }
marker_cut = { fg = "#d0eabf", bg = "#d0eabf" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#def8cc", bg = "#def8cc" }

# Count
count_copied = { fg = "#000000", bg = "#d0eabf" }
count_cut = { fg = "#000000", bg = "#d0eabf" }
count_selected = { fg = "#000000", bg = "#def8cc" }

# Border
border_symbol = " "
border_style  = { fg = "#f0bf6d" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffedd7", fg = "#000000", bold = true }
normal_alt  = { bg = "#4e4539", fg = "#ffffff" }

# Select mode
select_main = { bg = "#ffedd7", fg = "#000000", bold = true }
select_alt  = { bg = "#4e4539", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#def8cc", fg = "#000000", bold = true }
unset_alt  = { bg = "#4e4539", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffedd7", bg = "#564f45" }
progress_error = { fg = "#ffece9", bg = "#564f45" }

# Permissions
permissions_t = { fg = "#ffa83e" }
permissions_w = { fg = "#87e645" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#7bc44c" }
permissions_s = { fg = "#ffa212" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffedd7" }
active = { fg = "#def8cc", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffedd7" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffedd7", bold = true, bg = "#17130b" }
inactive = { fg = "#ffedd7", bg = "#17130b" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffedd7", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffedd7" }
title = {}
hovered = { fg = "#d0eabf", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#564f45" }
cand = { fg = "#ffedd7" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#ffedd7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#def8cc" }
title_warn = { fg = "#ffedd7" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#f0bf6d" },
]

# : ]]]
