# : Manager [[[

[mgr]
cwd = { fg = "#e1e3d9" }

# Tab
tab_active = { fg = "#1a3705", bg = "#acd28e", bold = true }
tab_inactive = { fg = "#c8eea8", bg = "#0b2000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6bd6d1", bg = "#6bd6d1" }
marker_cut = { fg = "#bbecea", bg = "#bbecea" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a0cfce", bg = "#a0cfce" }

# Count
count_copied = { fg = "#002020", bg = "#bbecea" }
count_cut = { fg = "#002020", bg = "#bbecea" }
count_selected = { fg = "#1a3705", bg = "#a0cfce" }

# Border
border_symbol = " "
border_style  = { fg = "#acd28e" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#1a3705", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#acd28e", fg = "#1a3705", bold = true }
normal_alt  = { bg = "#44483e", fg = "#c4c8bb" }

# Select mode
select_main = { bg = "#becbaf", fg = "#293420", bold = true }
select_alt  = { bg = "#44483e", fg = "#c4c8bb" }

# Unset mode
unset_main = { bg = "#a0cfce", fg = "#003737", bold = true }
unset_alt  = { bg = "#44483e", fg = "#c4c8bb" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#acd28e", bg = "#373a33" }
progress_error = { fg = "#ffb4ab", bg = "#373a33" }

# Permissions
permissions_t = { fg = "#728859" }
permissions_w = { fg = "#488e8d" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#43cbc5" }
permissions_s = { fg = "#77d429" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#acd28e" }
active = { fg = "#a0cfce", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#acd28e" }
value = { fg = "#e1e3d9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#acd28e", bold = true, bg = "#11140e" }
inactive = { fg = "#becbaf", bg = "#11140e" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#acd28e", bg = "#1a3705" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#acd28e" }
title = {}
hovered = { fg = "#bbecea", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#373a33" }
cand = { fg = "#acd28e" }
rest = { fg = "#1a3705" }
desc = { fg = "#e1e3d9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e3d9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e3d9" }
run = { fg = "#e1e3d9" }
footer = { fg = "#293420", bg = "#becbaf" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a0cfce" }
title_warn = { fg = "#acd28e" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e3d9" },
    { name = "*/", fg = "#acd28e" },
]

# : ]]]
