# : Manager [[[

[mgr]
cwd = { fg = "#dde4e4" }

# Tab
tab_active = { fg = "#00373a", bg = "#80d4da", bold = true }
tab_inactive = { fg = "#9cf0f6", bg = "#002022" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#709dff", bg = "#709dff" }
marker_cut = { fg = "#d6e3ff", bg = "#d6e3ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b6c7e9", bg = "#b6c7e9" }

# Count
count_copied = { fg = "#091b36", bg = "#d6e3ff" }
count_cut = { fg = "#091b36", bg = "#d6e3ff" }
count_selected = { fg = "#00373a", bg = "#b6c7e9" }

# Border
border_symbol = " "
border_style  = { fg = "#80d4da" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00373a", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#80d4da", fg = "#00373a", bold = true }
normal_alt  = { bg = "#3f4949", fg = "#bec8c9" }

# Select mode
select_main = { bg = "#b1cccd", fg = "#1b3436", bold = true }
select_alt  = { bg = "#3f4949", fg = "#bec8c9" }

# Unset mode
unset_main = { bg = "#b6c7e9", fg = "#20314c", bold = true }
unset_alt  = { bg = "#3f4949", fg = "#bec8c9" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#80d4da", bg = "#343a3b" }
progress_error = { fg = "#ffb4ab", bg = "#343a3b" }

# Permissions
permissions_t = { fg = "#598a8c" }
permissions_w = { fg = "#406dc6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3d7bff" }
permissions_s = { fg = "#15d6e4" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#80d4da" }
active = { fg = "#b6c7e9", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#80d4da" }
value = { fg = "#dde4e4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#80d4da", bold = true, bg = "#0e1415" }
inactive = { fg = "#b1cccd", bg = "#0e1415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#80d4da", bg = "#00373a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#80d4da" }
title = {}
hovered = { fg = "#d6e3ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3b" }
cand = { fg = "#80d4da" }
rest = { fg = "#00373a" }
desc = { fg = "#dde4e4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dde4e4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dde4e4" }
run = { fg = "#dde4e4" }
footer = { fg = "#1b3436", bg = "#b1cccd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b6c7e9" }
title_warn = { fg = "#80d4da" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dde4e4" },
    { name = "*/", fg = "#80d4da" },
]

# : ]]]
