# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#f5f59b", bold = true }
tab_inactive = { fg = "#e8e78f", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#70d5a8", bg = "#70d5a8" }
marker_cut = { fg = "#bfecd8", bg = "#bfecd8" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#cdfae6", bg = "#cdfae6" }

# Count
count_copied = { fg = "#000000", bg = "#bfecd8" }
count_cut = { fg = "#000000", bg = "#bfecd8" }
count_selected = { fg = "#000000", bg = "#cdfae6" }

# Border
border_symbol = " "
border_style  = { fg = "#cbcb76" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f5f59b", fg = "#000000", bold = true }
normal_alt  = { bg = "#48473a", fg = "#ffffff" }

# Select mode
select_main = { bg = "#f4f2cc", fg = "#000000", bold = true }
select_alt  = { bg = "#48473a", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#cdfae6", fg = "#000000", bold = true }
unset_alt  = { bg = "#48473a", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f5f59b", bg = "#515046" }
progress_error = { fg = "#ffece9", bg = "#515046" }

# Permissions
permissions_t = { fg = "#d9d24e" }
permissions_w = { fg = "#42eca0" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#49c990" }
permissions_s = { fg = "#b8b726" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f5f59b" }
active = { fg = "#cdfae6", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#f5f59b" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#f5f59b", bold = true, bg = "#14140c" }
inactive = { fg = "#f4f2cc", bg = "#14140c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f5f59b", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f5f59b" }
title = {}
hovered = { fg = "#bfecd8", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#515046" }
cand = { fg = "#f5f59b" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#f4f2cc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#cdfae6" }
title_warn = { fg = "#f5f59b" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#cbcb76" },
]

# : ]]]
