# : Manager [[[

[mgr]
cwd = { fg = "#161d1c" }

# Tab
tab_active = { fg = "#ffffff", bg = "#006a65", bold = true }
tab_inactive = { fg = "#9df2ea", bg = "#00201e" }
tab_width = 1

# Find
find_keyword = { fg = "#ba1a1a", bold = true, italic = true, underline = true }
find_position = { fg = "#ba1a1a", bold = true, italic = true }

# Marker
marker_copied = { fg = "#69abff", bg = "#69abff" }
marker_cut = { fg = "#cfe4ff", bg = "#cfe4ff" }
marker_marked = { fg = "#ba1a1a", bg = "#ba1a1a" }
marker_selected = { fg = "#48607b", bg = "#48607b" }

# Count
count_copied = { fg = "#001d34", bg = "#cfe4ff" }
count_cut = { fg = "#001d34", bg = "#cfe4ff" }
count_selected = { fg = "#ffffff", bg = "#48607b" }

# Border
border_symbol = " "
border_style  = { fg = "#006a65" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#ffffff", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#006a65", fg = "#ffffff", bold = true }
normal_alt  = { bg = "#dae5e3", fg = "#3f4947" }

# Select mode
select_main = { bg = "#4a6361", fg = "#ffffff", bold = true }
select_alt  = { bg = "#dae5e3", fg = "#3f4947" }

# Unset mode
unset_main = { bg = "#48607b", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#dae5e3", fg = "#3f4947" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#006a65", bg = "#f4fbf9" }
progress_error = { fg = "#ba1a1a", bg = "#f4fbf9" }

# Permissions
permissions_t = { fg = "#96b0ae" }
permissions_w = { fg = "#99adc3" }
permissions_x = { fg = "#ed8080" }
permissions_r = { fg = "#368eff" }
permissions_s = { fg = "#1dd9c7" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#006a65" }
active = { fg = "#48607b", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#006a65" }
value = { fg = "#161d1c" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#006a65", bold = true, bg = "#f4fbf9" }
inactive = { fg = "#4a6361", bg = "#f4fbf9" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#006a65", bg = "#ffffff" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#006a65" }
title = {}
hovered = { fg = "#cfe4ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#f4fbf9" }
cand = { fg = "#006a65" }
rest = { fg = "#ffffff" }
desc = { fg = "#161d1c" }
separator = " ‚ñ∂ "
separator_style = { fg = "#161d1c" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#161d1c" }
run = { fg = "#161d1c" }
footer = { fg = "#ffffff", bg = "#4a6361" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#48607b" }
title_warn = { fg = "#006a65" }
title_error = { fg = "#ba1a1a" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffdad6" },
    { name = "*", is = "exec", fg = "#410002" },

    # Fallback
    { name = "*", fg = "#161d1c" },
    { name = "*/", fg = "#006a65" },
]

# : ]]]
