# : Manager [[[

[mgr]
cwd = { fg = "#eae1d4" }

# Tab
tab_active = { fg = "#3d2e00", bg = "#e4c36c", bold = true }
tab_inactive = { fg = "#ffdf91", bg = "#241a00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7fd27c", bg = "#7fd27c" }
marker_cut = { fg = "#c9ecc8", bg = "#c9ecc8" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#aecfad", bg = "#aecfad" }

# Count
count_copied = { fg = "#04210b", bg = "#c9ecc8" }
count_cut = { fg = "#04210b", bg = "#c9ecc8" }
count_selected = { fg = "#3d2e00", bg = "#aecfad" }

# Border
border_symbol = " "
border_style  = { fg = "#e4c36c" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3d2e00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e4c36c", fg = "#3d2e00", bold = true }
normal_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Select mode
select_main = { bg = "#d6c5a0", fg = "#392f15", bold = true }
select_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Unset mode
unset_main = { bg = "#aecfad", fg = "#1a361e", bold = true }
unset_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e4c36c", bg = "#3d392f" }
progress_error = { fg = "#ffb4ab", bg = "#3d392f" }

# Permissions
permissions_t = { fg = "#9a7f43" }
permissions_w = { fg = "#568f54" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#59c556" }
permissions_s = { fg = "#f7af00" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e4c36c" }
active = { fg = "#aecfad", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#e4c36c" }
value = { fg = "#eae1d4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#e4c36c", bold = true, bg = "#16130b" }
inactive = { fg = "#d6c5a0", bg = "#16130b" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e4c36c", bg = "#3d2e00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e4c36c" }
title = {}
hovered = { fg = "#c9ecc8", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3d392f" }
cand = { fg = "#e4c36c" }
rest = { fg = "#3d2e00" }
desc = { fg = "#eae1d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#eae1d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eae1d4" }
run = { fg = "#eae1d4" }
footer = { fg = "#392f15", bg = "#d6c5a0" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#aecfad" }
title_warn = { fg = "#e4c36c" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eae1d4" },
    { name = "*/", fg = "#e4c36c" },
]

# : ]]]
