# : Manager [[[

[mgr]
cwd = { fg = "#f0dfd8" }

# Tab
tab_active = { fg = "#542103", bg = "#ffb692", bold = true }
tab_inactive = { fg = "#ffdbcb", bg = "#341000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#dbc956", bg = "#dbc956" }
marker_cut = { fg = "#ede4aa", bg = "#ede4aa" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d0c890", bg = "#d0c890" }

# Count
count_copied = { fg = "#1f1c00", bg = "#ede4aa" }
count_cut = { fg = "#1f1c00", bg = "#ede4aa" }
count_selected = { fg = "#542103", bg = "#d0c890" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb692" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#542103", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb692", fg = "#542103", bold = true }
normal_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# Select mode
select_main = { bg = "#e6beac", fg = "#432a1e", bold = true }
select_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# Unset mode
unset_main = { bg = "#d0c890", fg = "#353107", bold = true }
unset_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb692", bg = "#423732" }
progress_error = { fg = "#ffb4ab", bg = "#423732" }

# Permissions
permissions_t = { fg = "#bf633a" }
permissions_w = { fg = "#8c823b" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#d2bb2c" }
permissions_s = { fg = "#ff7132" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb692" }
active = { fg = "#d0c890", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb692" }
value = { fg = "#f0dfd8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb692", bold = true, bg = "#1a120e" }
inactive = { fg = "#e6beac", bg = "#1a120e" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb692", bg = "#542103" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb692" }
title = {}
hovered = { fg = "#ede4aa", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423732" }
cand = { fg = "#ffb692" }
rest = { fg = "#542103" }
desc = { fg = "#f0dfd8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f0dfd8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dfd8" }
run = { fg = "#f0dfd8" }
footer = { fg = "#432a1e", bg = "#e6beac" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d0c890" }
title_warn = { fg = "#ffb692" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dfd8" },
    { name = "*/", fg = "#ffb692" },
]

# : ]]]
